name: Plan & Apply GKE Resources

on: workflow_dispatch

jobs:
  Terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/app

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true


      # Get the GKE credentials so we can deploy to the cluster
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials dev-gke-001-cluster --zone asia-northeast1-b --project ${{ secrets.GCP_PROJECT }}

      - name: Confirm Kubeconfig
        run: ls -la ~

      - name: Confirm Kubeconfig
        run: ls -la $GITHUB_WORKSPACE

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      # Create input variables from Environment Secret
      # NOTE: Avoid terraform.tfvars
      - name: Setup Terraform variables
        run: cp terraform.tfvars.example terraform.auto.tfvars

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      # Apply the plan if merge to branch master
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Deployment Confirm
      - name: Deploy
        run: kubectl get services -o wide
